---
title: Rust异常处理与模式匹配
date: 2021-09-14 07:49:10

  - rust
categories:
  - blog
  - rust
---

> 只要能想到的意外，都会发生。

## 一、match 匹配处理错误

`File::open`函数返回值的类型是`Result<T, E>`。这里 T 的类型是`std::fs::File`,它是一个可以进行读写操作的文件句柄。E 的类型是`std::io::Error`,表示文件不存在或没有权限访问。

### match 匹配对返回值进行相应的处理

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let file = match f {
        Ok(file) => file,
        Err(error) => {
            panic!("Failed to open hello.txt: {:?}", error);
        }
    };
}
```

match 模式匹配虽然能够对返回值进行相应的处理，但是代码上看上去有些冗长。`Result<T,E>`类型提供的 unwrap 和 expect 方法可以实现与 match 模式匹配相似的功能。

### 使用`unwrap`改进

如果 Result 的值是 Ok，unwrap 方法会返回 Ok 中的值。如果 Result 的值是 Err，unwrap 方法会自动做 Panic 处理并输出默认的错误消息。

```rust
use std::fs::File;

fn main() {
    // 如果异常自动panic
    let f = File::open("hello.txt").unwrap();
}
```

### 使用`except`改进

except 方法不仅具备 unwrap 方法的功能，还允许自定义错误的信息，这样更易于追踪导致程序错误的原因。

```rust
use std::fs::File;

fn main() {
    // 如果异常自动panic,并给出自定义错误信息
    let f = File::open("hello.txt").expect("Failed to open hello.txt");
}
```

## 二、模式匹配传播错误

我们来写一个把文件内容读到一个字符串的程序，如果出现错误则返回`io::Error`，否则返回`String`即读到的内容。

### match 匹配传播错误

```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn main() {
    println!("content: {}", read_from_file().unwrap());
}

fn read_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");
    let mut file = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };
    let mut s = String::new();
    match file.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```

### 使用`?`操作符来改进

考虑到错误传播在编程中非常常见，Rust 提供了`?`操作符来简化代码。`?`操作符可以用于返回值类型为 Result 的函数中，它被定义为与 match 匹配完全相同的工作方式。如果 Result 的值是 OK，将返回 Ok 中的值并继续执行下面的代码。如果 Result 的值是 Err,Err 中的值将作为整个函数的返回值传给调用者。

```python
fn read_from_file() -> Result<String, io::Error> {
    let mut s = String::new();
    File::open("hello.txt")?.read_to_string(&mut s)?;
    Ok(s)
}
```

漂亮，10 行代码，变为 3 行，做的是同样的事。
